# Generated by Django 4.2.16 on 2024-09-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(default='Odio ultrices ut. Etiam ac erat ut enim maximus accumsan vel ac nisl. Duis feug iat bibendum orci, non elementum urna. Cras sit amet sapien aliquam.')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Site Contact',
                'verbose_name_plural': 'Site Contacts',
            },
        ),
    ]
