# Generated by Django 4.2.16 on 2024-09-24 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title Reviews')),
                ('text', models.TextField(verbose_name='text Reviews')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='rating Reviews')),
                ('image', models.ImageField(upload_to='review_backgrounds/', verbose_name='image Reviews')),
            ],
        ),
    ]
