# Generated by Django 4.2.16 on 2024-09-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviews_created_at_alter_reviews_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
