# Generated by Django 4.2.16 on 2024-09-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='rating',
        ),
    ]
