# Generated by Django 4.2.16 on 2024-09-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_games_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tournament Title')),
                ('image', models.ImageField(upload_to='tournaments_backgrounds/', verbose_name='image Recent')),
                ('start_date', models.DateField(verbose_name='Tournament Begins')),
                ('end_date', models.DateField(verbose_name='Tournament Ends')),
                ('participants_count', models.IntegerField(verbose_name='Participants')),
                ('author', models.CharField(max_length=100, verbose_name='Tournament Author')),
                ('first_place_prize', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='1st Place Prize')),
                ('second_place_prize', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='2nd Place Prize')),
                ('third_place_prize', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='3rd Place Prize')),
            ],
        ),
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.ImageField(upload_to='games_backgrounds/', verbose_name='image Recent'),
        ),
    ]
