# Generated by Django 4.2.16 on 2024-09-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_tournaments_alter_games_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournaments',
            options={'ordering': ['-start_date'], 'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournaments'},
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_news', models.CharField(max_length=255, verbose_name='Body news')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.gamesgenre', verbose_name='News genre')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-created_at'],
            },
        ),
    ]
